In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("flights.csv")

In [4]:
df.shape

(5819079, 31)

In [5]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [6]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.drop(['TAXI_OUT','TAXI_IN','WHEELS_OFF','WHEELS_ON','ELAPSED_TIME'], axis=1)

In [8]:
df = df.drop(['SCHEDULED_TIME','AIR_TIME'], axis=1)

In [9]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [10]:
import pandas as pd

def convert_time(value):
    if pd.isna(value):
        return None

    value = str(value)

    # Already converted
    if ':' in value:
        return value

    value = value.split('.')[0]  # remove .0 if float
    value = value.zfill(4)

    return f"{value[:2]}:{value[2:]}"

In [11]:
df['SCHEDULED_DEPARTURE'] = df['SCHEDULED_DEPARTURE'].apply(convert_time)
df['DEPARTURE_TIME'] = df['DEPARTURE_TIME'].apply(convert_time)

In [12]:
df['SCHEDULED_ARRIVAL'] = df['SCHEDULED_ARRIVAL'].apply(convert_time)
df['ARRIVAL_TIME'] = df['ARRIVAL_TIME'].apply(convert_time)

In [13]:
df['SCHEDULED_DEPARTURE'].head(10)

0    00:05
1    00:10
2    00:20
3    00:20
4    00:25
5    00:25
6    00:25
7    00:30
8    00:30
9    00:30
Name: SCHEDULED_DEPARTURE, dtype: object

In [14]:
df['DIVERTED'].value_counts()

DIVERTED
0    5803892
1      15187
Name: count, dtype: int64

In [15]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [16]:
df.dropna(subset=['TAIL_NUMBER'], inplace=True)

In [17]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER                  0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           71432
DEPARTURE_DELAY          71432
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             77792
ARRIVAL_DELAY            90350
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4740919
SECURITY_DELAY         4740919
AIRLINE_DELAY          4740919
LATE_AIRCRAFT_DELAY    4740919
WEATHER_DELAY          4740919
dtype: int64

In [18]:
df['DEPARTURE_TIME'] = df['DEPARTURE_TIME'].replace('Flight Canceled', 0)

In [19]:
df.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE     object
DEPARTURE_TIME          object
DEPARTURE_DELAY        float64
DISTANCE                 int64
SCHEDULED_ARRIVAL       object
ARRIVAL_TIME            object
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [20]:
df['DEPARTURE_TIME'].head(30)

0     23:54
1     00:02
2     00:18
3     00:15
4     00:24
5     00:20
6     00:19
7     00:44
8     00:19
9     00:33
10    00:24
11    00:27
12    00:35
13    00:34
14    00:39
15    00:41
16    00:31
17    00:42
18    00:46
19    00:45
20    01:20
21    00:52
22    01:02
23    01:03
24    01:02
25    01:12
26    01:07
27    01:27
28    01:10
29    01:41
Name: DEPARTURE_TIME, dtype: object

In [21]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER                  0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           71432
DEPARTURE_DELAY          71432
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             77792
ARRIVAL_DELAY            90350
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4740919
SECURITY_DELAY         4740919
AIRLINE_DELAY          4740919
LATE_AIRCRAFT_DELAY    4740919
WEATHER_DELAY          4740919
dtype: int64

In [22]:
df['DEPARTURE_DELAY'] = df['DEPARTURE_DELAY'].fillna(0)

In [23]:
df.loc[(df['ARRIVAL_TIME'].isnull()) & (df['CANCELLED'] == 1), 'ARRIVAL_TIME'] = '00:00'

In [24]:
print(df[['ARRIVAL_TIME', 'DEPARTURE_TIME']].isnull().sum())

ARRIVAL_TIME       2629
DEPARTURE_TIME    71432
dtype: int64

In [25]:
df['ARRIVAL_TIME'] = df['ARRIVAL_TIME'].fillna(0)

In [26]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER                  0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           71432
DEPARTURE_DELAY              0
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME                 0
ARRIVAL_DELAY            90350
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4740919
SECURITY_DELAY         4740919
AIRLINE_DELAY          4740919
LATE_AIRCRAFT_DELAY    4740919
WEATHER_DELAY          4740919
dtype: int64

In [27]:
df[df['ARRIVAL_TIME'].isnull()]

Empty DataFrame
Columns: [YEAR, MONTH, DAY, DAY_OF_WEEK, AIRLINE, FLIGHT_NUMBER, TAIL_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, SCHEDULED_DEPARTURE, DEPARTURE_TIME, DEPARTURE_DELAY, DISTANCE, SCHEDULED_ARRIVAL, ARRIVAL_TIME, ARRIVAL_DELAY, DIVERTED, CANCELLED, CANCELLATION_REASON, AIR_SYSTEM_DELAY, SECURITY_DELAY, AIRLINE_DELAY, LATE_AIRCRAFT_DELAY, WEATHER_DELAY]
Index: []

[0 rows x 24 columns]

In [28]:
df['DIVERTED'].value_counts()

DIVERTED
0    5789171
1      15187
Name: count, dtype: int64

In [29]:
df.loc[(df['ARRIVAL_DELAY'].isnull()) & (df['CANCELLED'] == 1), 'ARRIVAL_DELAY'] = 0

In [30]:
print(df[['ARRIVAL_TIME', 'DEPARTURE_TIME']].isnull().sum())

ARRIVAL_TIME          0
DEPARTURE_TIME    71432
dtype: int64

In [31]:
df['ARRIVAL_DELAY'] = df['ARRIVAL_DELAY'].fillna(0)

In [32]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER                  0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           71432
DEPARTURE_DELAY              0
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME                 0
ARRIVAL_DELAY                0
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4740919
SECURITY_DELAY         4740919
AIRLINE_DELAY          4740919
LATE_AIRCRAFT_DELAY    4740919
WEATHER_DELAY          4740919
dtype: int64

In [33]:
df['ARRIVAL_TIME'].dtypes

dtype('O')

In [34]:
df['CANCELLATION_REASON'] = df['CANCELLATION_REASON'].fillna('Not Canceled')

In [35]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER                  0
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           71432
DEPARTURE_DELAY              0
DISTANCE                     0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME                 0
ARRIVAL_DELAY                0
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON          0
AIR_SYSTEM_DELAY       4740919
SECURITY_DELAY         4740919
AIRLINE_DELAY          4740919
LATE_AIRCRAFT_DELAY    4740919
WEATHER_DELAY          4740919
dtype: int64

In [36]:
df['AIR_SYSTEM_DELAY'] = df['AIR_SYSTEM_DELAY'].fillna(0)
df['SECURITY_DELAY'] = df['SECURITY_DELAY'].fillna(0)
df['AIRLINE_DELAY'] = df['AIRLINE_DELAY'].fillna(0)
df['LATE_AIRCRAFT_DELAY'] = df['LATE_AIRCRAFT_DELAY'].fillna(0)
df['WEATHER_DELAY'] = df['WEATHER_DELAY'].fillna(0)

In [37]:
df.isnull().sum()

YEAR                       0
MONTH                      0
DAY                        0
DAY_OF_WEEK                0
AIRLINE                    0
FLIGHT_NUMBER              0
TAIL_NUMBER                0
ORIGIN_AIRPORT             0
DESTINATION_AIRPORT        0
SCHEDULED_DEPARTURE        0
DEPARTURE_TIME         71432
DEPARTURE_DELAY            0
DISTANCE                   0
SCHEDULED_ARRIVAL          0
ARRIVAL_TIME               0
ARRIVAL_DELAY              0
DIVERTED                   0
CANCELLED                  0
CANCELLATION_REASON        0
AIR_SYSTEM_DELAY           0
SECURITY_DELAY             0
AIRLINE_DELAY              0
LATE_AIRCRAFT_DELAY        0
WEATHER_DELAY              0
dtype: int64

In [38]:
df.to_csv("Final_Flights_Cleaned.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'Final_Flights_Cleaned.csv'

In [39]:
df = pd.read_csv("Final_Flights_Cleaned.csv")

In [40]:
df.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE     object
DEPARTURE_TIME          object
DEPARTURE_DELAY        float64
DISTANCE                 int64
SCHEDULED_ARRIVAL       object
ARRIVAL_TIME            object
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object